# Generated by Django 5.2.3 on 2025-06-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('Homepage', 'Homepage'), ('About', 'About'), ('Projects', 'Projects'), ('Properties', 'Properties'), ('Blog', 'Blog'), ('Services', 'Services'), ('Contact', 'Contact'), ('Careers', 'Careers')], default='Homepage', max_length=22, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=160)),
                ('og_title', models.CharField(max_length=60)),
                ('og_description', models.CharField(max_length=160)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
