# Generated by Django 5.2.3 on 2025-06-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'Seo', 'verbose_name_plural': 'Seo'},
        ),
    ]
