# Generated by Django 5.2.3 on 2025-06-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_alter_seo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=60, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'ClientFeedback',
                'verbose_name_plural': 'ClientFeedbacks',
            },
        ),
    ]
