# Generated by Django 5.2.3 on 2025-06-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_clientfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='subject',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
