# Generated by Django 5.2.3 on 2025-06-15 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Banner title')),
                ('title_gold', models.CharField(blank=True, max_length=256, null=True, verbose_name='Banner title gold')),
                ('image', models.ImageField(upload_to='Banners', verbose_name='Banner image')),
            ],
            options={
                'verbose_name': 'Main Banner',
                'verbose_name_plural': 'Main Banner',
            },
        ),
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('og_title', models.CharField(max_length=100)),
                ('og_description', models.TextField()),
                ('og_image', models.ImageField(upload_to='Meta', verbose_name='OG image')),
            ],
            options={
                'verbose_name': 'Page meta',
                'verbose_name_plural': 'Page meta',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Position title')),
                ('department', models.CharField(max_length=128, verbose_name='Position department')),
                ('location', models.CharField(max_length=128, verbose_name='Position location')),
                ('type', models.CharField(max_length=128, verbose_name='Position type Full-time || Part-Time')),
                ('experience', models.CharField(max_length=128, verbose_name='Position experience')),
                ('overview', models.CharField(max_length=512, verbose_name='Position overview')),
                ('requirements', models.TextField(verbose_name='Position requirements')),
                ('benefits', models.TextField(verbose_name='Position benefits')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Opened Positions',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=128, verbose_name='Phone')),
                ('experience', models.CharField(max_length=128, verbose_name='Experience')),
                ('linkedin', models.CharField(blank=True, max_length=256, null=True, verbose_name='Linkedin profile')),
                ('portfolio', models.CharField(blank=True, max_length=256, null=True, verbose_name='Portfolio || Website')),
                ('cover_letter', models.CharField(max_length=256, verbose_name='Cover Letter')),
                ('resume', models.FileField(upload_to='resumes', verbose_name='Resume File || CV')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.position', verbose_name='Applied Position')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applied Applications',
            },
        ),
    ]
