# Generated by Django 5.2.3 on 2025-06-16 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_application_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.position', verbose_name='Applied Position'),
        ),
    ]
