# Generated by Django 5.2.3 on 2025-06-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_application_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.CharField(max_length=512, verbose_name='Position title'),
        ),
    ]
