# Generated by Django 5.2.3 on 2025-06-16 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='City Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Developer Name')),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
            },
        ),
        migrations.CreateModel(
            name='DownloadedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get all the floor plans', max_length=256, verbose_name='Title')),
                ('image', models.ImageField(upload_to='downloaded_images', verbose_name='Downloaded Image')),
                ('buttonText', models.CharField(default='Download floor plans', max_length=256, verbose_name='Button Text')),
            ],
            options={
                'verbose_name': 'Downloaded Information',
                'verbose_name_plural': 'Downloaded Information',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Property Type')),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Types',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('location', models.CharField(max_length=100, verbose_name='Project Location')),
                ('card_overview', models.CharField(max_length=100, verbose_name='Project Card Overview')),
                ('card_property_type', models.CharField(default='Apartments', max_length=100, verbose_name='Project Card Property Type')),
                ('starting_price', models.BigIntegerField(verbose_name='Price from')),
                ('handover', models.CharField(max_length=100, verbose_name='Handover')),
                ('card_image', models.ImageField(upload_to='card_images', verbose_name='Card Image')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured ?')),
                ('status', models.CharField(default='Off-plan', max_length=100, verbose_name='Project Status')),
                ('amenities', models.TextField(verbose_name='Amenities')),
                ('map_location', models.CharField(max_length=100, verbose_name='Map Location')),
                ('mainBanner', models.ImageField(upload_to='main_banner', verbose_name='Main Banner')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.developer', verbose_name='Developer')),
                ('property_types', models.ManyToManyField(to='projects.propertytype', verbose_name='Property Types')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Place Name')),
                ('type', models.CharField(max_length=256, verbose_name='Place Type')),
                ('distance', models.CharField(max_length=256, verbose_name='Place Distance')),
                ('travelTime', models.CharField(max_length=256, verbose_name='Place Travel Time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='projects.project', verbose_name='Project Nearby Places')),
            ],
            options={
                'verbose_name': 'Nearby Place',
                'verbose_name_plural': 'Nearby Places',
            },
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_gallery', verbose_name='Project Gallery')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_gallery', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Gallery',
                'verbose_name_plural': 'Project Gallery',
            },
        ),
        migrations.CreateModel(
            name='SimilarProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Related Projects You May Like', max_length=256, verbose_name='Title')),
                ('projects', models.ManyToManyField(to='projects.project', verbose_name='Related Projects')),
            ],
        ),
    ]
