# Generated by Django 5.2.3 on 2025-06-16 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedinformation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_informations', to='projects.project', verbose_name='Project'),
            preserve_default=False,
        ),
    ]
