# Generated by Django 5.2.3 on 2025-06-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_downloadedinformation_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='similarprojects',
            options={'verbose_name': 'Similar Project', 'verbose_name_plural': 'Similar Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1, max_length=100, verbose_name='Project Slug'),
            preserve_default=False,
        ),
    ]
