# Generated by Django 5.2.3 on 2025-06-18 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_alter_similarprojects_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.city', verbose_name='City'),
            preserve_default=False,
        ),
    ]
