# Generated by Django 5.2.3 on 2025-06-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_city_alter_project_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedinformation',
            name='file',
            field=models.FileField(default=1, upload_to='downloaded_files', verbose_name='Downloaded File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadedinformation',
            name='image',
            field=models.ImageField(upload_to='downloaded_images', verbose_name='Background Image'),
        ),
    ]
