# Generated by Django 5.2.3 on 2025-06-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_downloadedinformation_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=1, verbose_name='Project Description'),
            preserve_default=False,
        ),
    ]
