# Generated by Django 5.2.3 on 2025-06-16 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0009_alter_property_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Banner title')),
                ('title_gold', models.CharField(blank=True, max_length=256, null=True, verbose_name='Banner title gold')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Banner description')),
                ('image', models.ImageField(upload_to='Banners', verbose_name='Banner image')),
            ],
            options={
                'verbose_name': 'Main Banner',
                'verbose_name_plural': 'Main Banner',
            },
        ),
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('og_title', models.CharField(max_length=100)),
                ('og_description', models.TextField()),
                ('og_image', models.ImageField(upload_to='Meta', verbose_name='OG image')),
            ],
            options={
                'verbose_name': 'Page meta',
                'verbose_name_plural': 'Page meta',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Service name')),
                ('description', models.TextField(verbose_name='Service description')),
                ('detailedDescription', models.TextField(verbose_name='Service detailed description')),
                ('keyBenefits', models.TextField(verbose_name='Service keyBenefits')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='AdditionalProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Additional properties section title')),
                ('properties', models.ManyToManyField(to='properties.property', verbose_name='Additional properties')),
            ],
            options={
                'verbose_name': 'Additional properties',
                'verbose_name_plural': 'Additional properties',
            },
        ),
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Step title')),
                ('description', models.TextField(verbose_name='Step description')),
                ('image', models.ImageField(upload_to='Steps', verbose_name='Step image')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processSteps', to='services.service')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
            },
        ),
    ]
