# Generated by Django 5.2.3 on 2025-06-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproperties',
            name='description',
            field=models.TextField(default=1, verbose_name='Additional properties section description'),
            preserve_default=False,
        ),
    ]
