# Generated by Django 5.2.3 on 2025-06-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='card_image',
            field=models.ImageField(default=1, upload_to='Service', verbose_name='Service card image'),
            preserve_default=False,
        ),
    ]
