# Generated by Django 5.2.3 on 2025-06-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_faqs_overview_remove_faqs_title_faqs_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=1, max_length=256, verbose_name='Service slug'),
            preserve_default=False,
        ),
    ]
