# Generated by Django 5.2.3 on 2025-06-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Service slug'),
        ),
    ]
