# Generated by Django 5.2.3 on 2025-06-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalproperties',
            name='properties',
        ),
        migrations.DeleteModel(
            name='PageMeta',
        ),
        migrations.DeleteModel(
            name='AdditionalProperties',
        ),
    ]
