# Generated by Django 5.2.3 on 2025-06-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='Categories', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('og_title', models.CharField(max_length=100)),
                ('og_description', models.TextField()),
                ('og_image', models.ImageField(upload_to='Meta', verbose_name='OG image')),
            ],
            options={
                'verbose_name': 'Page meta',
                'verbose_name_plural': 'Page meta',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('card_image', models.ImageField(upload_to='Blog', verbose_name='Card image')),
                ('banner_image', models.ImageField(upload_to='Blog', verbose_name='Banner image')),
                ('slug', models.SlugField(unique=True)),
                ('overview', models.TextField()),
                ('created', models.DateTimeField()),
                ('author_fullname', models.CharField(max_length=128)),
                ('author_position', models.CharField(max_length=128)),
                ('author_overview', models.CharField(max_length=1000)),
                ('author_image', models.ImageField(upload_to='Blog', verbose_name='Author')),
                ('time_of_read', models.CharField(max_length=128)),
                ('details', models.TextField()),
                ('keywords', models.TextField()),
                ('image', models.ImageField(upload_to='Blog', verbose_name='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('tags', models.ManyToManyField(to='blog.tag')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
