# Generated by Django 5.2.3 on 2025-06-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='page_title',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
