# Generated by Django 5.2.3 on 2025-06-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.ManyToManyField(to='blog.tag')),
            ],
            options={
                'verbose_name': 'Popular tags',
                'verbose_name_plural': 'Popular tags',
            },
        ),
    ]
