# Generated by Django 5.2.3 on 2025-06-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_category_alter_blog_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageMeta',
        ),
    ]
