# Generated by Django 5.2.3 on 2025-06-14 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertylocation',
            options={'verbose_name': 'Property Location', 'verbose_name_plural': 'Property Locations'},
        ),
        migrations.AlterModelOptions(
            name='propertystatus',
            options={'verbose_name': 'Property Status', 'verbose_name_plural': 'Property Status'},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name': 'Property Type', 'verbose_name_plural': 'Property Types'},
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='distance',
            field=models.CharField(max_length=256, verbose_name='Place Distance'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Place Name'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='properties.property', verbose_name='Property Nearby Place'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='travelTime',
            field=models.CharField(max_length=256, verbose_name='Place Travel Time'),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='type',
            field=models.CharField(max_length=256, verbose_name='Place Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.TextField(verbose_name='Building Amenities'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(max_length=12, verbose_name='Property Area - sq.f'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(verbose_name='Bathrooms Count'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(verbose_name='Bedrooms Count'),
        ),
        migrations.AlterField(
            model_name='property',
            name='card_image',
            field=models.ImageField(upload_to='property/', verbose_name='Property Card Image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.TextField(verbose_name='Property Features'),
        ),
        migrations.AlterField(
            model_name='property',
            name='for_rent',
            field=models.BooleanField(default=False, verbose_name='Property For Rent ?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertylocation', verbose_name='Property Location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='map',
            field=models.TextField(verbose_name='Property Google Map location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=512, unique=True, verbose_name='Property Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='overview',
            field=models.TextField(verbose_name='Property Overview'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Property Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ref',
            field=models.CharField(max_length=120, unique=True, verbose_name='Property Reference Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertystatus', verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype', verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='propertygallery',
            name='image',
            field=models.ImageField(upload_to='property/', verbose_name='Property Gallery Image'),
        ),
        migrations.AlterField(
            model_name='propertygallery',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='properties.property', verbose_name='Property Gallery'),
        ),
        migrations.AlterField(
            model_name='propertylocation',
            name='location',
            field=models.CharField(max_length=256, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='propertystatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Property Type'),
        ),
    ]
