# Generated by Django 5.2.3 on 2025-06-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertylocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Property Price'),
        ),
    ]
