# Generated by Django 5.2.3 on 2025-06-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(verbose_name='Property Price'),
        ),
    ]
