# Generated by Django 5.2.3 on 2025-06-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='property/', verbose_name='Property Card Image'),
        ),
        migrations.AlterField(
            model_name='propertygallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property/', verbose_name='Property Gallery Image'),
        ),
    ]
