# Generated by Django 5.2.3 on 2025-06-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_card_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='map',
            field=models.TextField(blank=True, null=True, verbose_name='Property Google Map location'),
        ),
    ]
