# Generated by Django 5.2.3 on 2025-06-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=256, verbose_name='Property Location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Off-plan', 'Off-plan')], max_length=20, verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(max_length=120, verbose_name='Property Type'),
        ),
        migrations.DeleteModel(
            name='PropertyLocation',
        ),
        migrations.DeleteModel(
            name='PropertyStatus',
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
    ]
