# Generated by Django 5.2.3 on 2025-06-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_property_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nearbyplace',
            options={'verbose_name': 'Place Nearby Place', 'verbose_name_plural': 'Place Nearby'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertygallery',
            options={'verbose_name': 'Property Gallery', 'verbose_name_plural': 'Property Galleries'},
        ),
    ]
