# Generated by Django 5.2.3 on 2025-06-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_nearbyplace_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('Properties', 'Properties'), ('Blog', 'Blog'), ('Services', 'Services')], default='Properties', max_length=22, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='Additional properties section title')),
                ('description', models.TextField(verbose_name='Additional properties section description')),
                ('properties', models.ManyToManyField(to='properties.property', verbose_name='Additional properties')),
            ],
            options={
                'verbose_name': 'Additional properties',
                'verbose_name_plural': 'Additional properties',
            },
        ),
    ]
