# Generated by Django 5.2.3 on 2025-06-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
