# Generated by Django 5.2.3 on 2025-06-20 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_mainbanner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersbanner',
            name='subtitle',
        ),
    ]
