# Generated by Django 5.2.3 on 2025-06-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_partnersbanner_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='slogan',
            field=models.CharField(default=1, max_length=512, verbose_name='Slogan'),
            preserve_default=False,
        ),
    ]
