# Generated by Django 5.2.3 on 2025-06-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_mainbanner_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Title'),
        ),
    ]
