# Generated by Django 5.2.3 on 2025-06-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_mainbanner_title'),
        ('services', '0007_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesbanner',
            name='services',
            field=models.ManyToManyField(to='services.service', verbose_name='Services'),
        ),
    ]
