# Generated by Django 5.2.3 on 2025-06-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
                ('overview', models.TextField()),
                ('image', models.ImageField(upload_to='team_images')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=256, verbose_name='Banner title')),
                ('banner_title_gold', models.CharField(max_length=256, verbose_name='Banner title gold')),
                ('banner_image', models.CharField(max_length=256, verbose_name='Banner image')),
                ('welcome_section_title', models.CharField(max_length=256, verbose_name='Welcome section title')),
                ('welcome_section_title_gold', models.CharField(max_length=256, verbose_name='Welcome section title gold')),
                ('welcome_section_description', models.CharField(max_length=256, verbose_name='Welcome section description')),
                ('our_mission', models.CharField(max_length=1052, verbose_name='Our mission')),
                ('our_vision', models.CharField(max_length=1052, verbose_name='Our vision')),
                ('our_values', models.CharField(max_length=1052, verbose_name='Our values')),
                ('founder_image', models.ImageField(upload_to='founder', verbose_name='Founder image')),
                ('founder_main_words', models.TextField(verbose_name='Founder main words')),
                ('founder_sub_words', models.TextField(verbose_name='Founder sub words')),
                ('team', models.ManyToManyField(to='about.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About page',
            },
        ),
    ]
