# Generated by Django 5.2.3 on 2025-06-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='banner_image',
            field=models.ImageField(upload_to='banners', verbose_name='Banner image'),
        ),
    ]
