# Generated by Django 5.2.3 on 2025-06-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpage_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='welcome_section_description',
            field=models.TextField(verbose_name='Welcome section description'),
        ),
    ]
